algo: kfac

algo_config:
  ent_coef: 0.00
  norm_obj: adv # options: adv, obj
  optimizer: kfac
  weight_decay: 0.0
  lr_pi: 0.01
  lr_v: 0.001
  use_kl_adaptive_lr: True
  is_karzmarz: False
  pi_epochs: 4
  pi_minibatches: 8
  v_epochs: 4
  v_minibatches: 8
  with_popart: True
  adv_type: gae
  clamp_ratio: True
  max_ratio: 10.0
  min_ratio: 0.1
  sigma_type: 'vector' # mu_shared, separate, linear
  cg_damping: 0.1
  grad: 'npg' # 'npg'
  post_grad: 'fisher_clip' # 'l2_clip', 'norm', 'fisher_clip'
  max_grad_norm: 0.5

env_config: 
  # env_name: mountaincar
  # env_name: carracing
  # env_name: cartpole
  env_name: hopper
  num_envs: 32
  nsteps: 256
  timesteps_per_proc: 10_000_000
  norm_ret: False

nets_config:
  norm_obs: True
  type: mlp
  a_dropout: 0.0
  a_hidden_size: 256
  a_num_layers: 2
  c_hidden_size: 256
  c_num_layers: 2
  c_dropout: 0.0

log_config: 
  log_interval: 10
  n_eval_trials: 20